apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pres
  namespace: ns-jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/mousam3/Documents/save-jenkins/jenkins"